### ISSUE TITLE
_get_3d_bbs

### ISSUE THREAD

**Issue by a1wj1** [OpenDriveLab/DriveAdapter#1]
Hello, may I ask if in function _get_3d_bbs（roach_ap_agent_data_collection.py）, relative_pos is the relative position of other objects to the ego vehicle? If so, how are the x and y coordinate axes represented?

**Comment by jiaxiaosong1002** [comment]
Again, [as I have explained to you](https://github.com/OpenDriveLab/ThinkTwice/issues/11), I only use it for visualizations  at the very early stage of the project. Please check these related functions by yourself since I do not use 3d_bbs related function in the final, which I could give any ensurement about its current correctness.
