### ISSUE TITLE
Evaluation problem

### ISSUE THREAD

**Issue by Reezzz702** [OpenDriveLab/DriveAdapter#2]
Hi, thanks for the greate work from your team. I would like to run the evaluation of your model, however it report segmentation fault either when it try to launch carla or it successfully launched carla but crash after certain steps (after stored 0011.png of topdown view). This happen every time I run the evaluation, wonder if you have any clue about it.

Also, if I would like to run evaluation of the teacher model, do I need to do other setting besides changing the agent to roach_ap_agent_data_collection.py and set CHALLENGE_TRACK_CODENAME to MAP?

**Comment by jiaxiaosong1002** [comment]
Hi, thanks for your interests!

The issue of crashing after certain steps is an known [issue](https://github.com/OpenDriveLab/ThinkTwice/issues/3) and we are not sure how to solve it since it is from the CARLA side and is highly related to device/system. You could try some possible solutions and maybe ask in the issue part of CARLA.

As for evaluation of the teacher model, you do not need to set CHALLENGE_TRACK_CODENAME to MAP. However, there some changes you should make:
```shell
control = self.process_act(actions) ## Original Line
## Set max speed since Roach is too reckless as we conducted for the student model.
if float(tick_data['speed']) > 3.0:
    max_throttle = 0.05
else:
    max_throttle = 0.75
control.throttle = np.clip(control.throttle, a_min=0.0, a_max=max_throttle)
```
Also, you may not want to collect raw sensor data as it would be very slow and consume lots of disk space for saving. There might be some function/variable dependency of Roach you may need to modify, which is usually straight-forward.
